# SERVICES
keepalived:
  labels:
    io.rancher.scheduler.global: 'true'
  environment:
    - VIRTUAL_IP=172.18.1.68
    - CHECK_PORT=3000
    - VRID=150
    - INTERFACE=eno16777984
  tty: true
  build: docker-keepalived
  stdin_open: true
  net: host
  cap_add:
  - NET_ADMIN
  - NET_BROADCAST
